package com.advanced_baseball_stats.v2.repository.stats.tables

import com.advanced_baseball_stats.v2.repository.customTypes.SafeRealSqlType
import org.ktorm.schema.Table
import org.ktorm.schema.int
import org.ktorm.schema.varchar
import org.ktorm.schema.double

object SeasonStatsPitchingTable : Table<Nothing>("SeasonStatsPitching")
{
    val key = varchar("key")
    val season = int("season")
    val playerId = varchar("playerId")
    val teams = varchar("teams")
    val ipOuts = int("ipOuts")
    val battersFaced = int("battersFaced")
    val hits = int("hits")
    val singles = int("singles")
    val doubles = int("doubles")
    val triples = int("triples")
    val homeRuns = int("homeRuns")
    val runs = int("runs")
    val earnedRuns = int("earnedRuns")
    val walks = int("walks")
    val intentionalWalks = int("intentionalWalks")
    val strikeOuts = int("strikeOuts")
    val hitByPitch = int("hitByPitch")
    val wildPitches = int("wildPitches")
    val balks = int("balks")
    val sacrificeHits = int("sacrificeHits")
    val sacrificeFlies = int("sacrificeFlies")
    val stolenBases = int("stolenBases")
    val caughtStealing = int("caughtStealing")
    val passedBalls = int("passedBalls")
    val wins = int("wins")
    val losses = int("losses")
    val saves = int("saves")
    val holds = int("holds")
    val gamesStarted = int("gamesStarted")
    val gamesFinished = int("gamesFinished")
    val completeGames = int("completeGames")
    val qualityStarts = int("qualityStarts")
    val era = double("era")
    val whip = double("whip")
    val ksPerNine = double("ksPerNine")
    val walksPerNine = double("walksPerNine")
    val homeRunsPerNine = double("homeRunsPerNine")
    val averageFastballVelocity = double("averageFastballVelocity")
    val averageExitVelocity = double("averageExitVelocity")
    val zonePercentage = double("zonePercentage")
    val chasePercentage = double("chasePercentage")
    val swingingStrikePercentage = double("swingingStrikePercentage")
    val hardHitPercentage = double("hardHitPercentage")
    val barrelPercentage = double("barrelPercentage")
    val groundBallPercentage = double("groundBallPercentage")
    val flyBallPercentage = double("flyBallPercentage")
    val lineDrivePercentage = double("lineDrivePercentage")
    val popUpPercentage = double("popUpPercentage")
    val strikeOutPercentage = double("strikeOutPercentage")
    val walkPercentage = double("walkPercentage")
    val strikeOutWalkDifference = double("strikeOutWalkDifference")
    val homeRunPerFlyBallPercentage = registerColumn("homeRunPerFlyBallPercentage", SafeRealSqlType)
}
