package com.advanced_baseball_stats.repository.tables

import org.ktorm.schema.Table
import org.ktorm.schema.int
import org.ktorm.schema.varchar

object ChadwickTable : Table<Nothing>("chadwick")
{
    val key_person = varchar("key_person")
    val key_uuid = varchar("key_uuid")
    val key_mlbam = varchar("key_mlbam")
    val key_retro = varchar("key_retro")
    val key_bbref = varchar("key_bbref")
    val key_bbref_minors = varchar("key_bbref_minors")
    val key_fangraphs = varchar("key_fangraphs")
    val key_npb = varchar("key_npb")
    val key_sr_nfl = varchar("key_sr_nfl")
    val key_sr_nba = varchar("key_sr_nba")
    val key_sr_nhl = varchar("key_sr_nhl")
    val key_wikidata = varchar("key_wikidata")
    val name_last = varchar("name_last")
    val name_first = varchar("name_first")
    val name_given = varchar("name_given")
    val name_suffix = varchar("name_suffix")
    val name_matrilineal = varchar("name_matrilineal")
    val name_nick = varchar("name_nick")
    val birth_year = varchar("birth_year")
    val birth_month = varchar("birth_month")
    val birth_day = varchar("birth_day")
    val death_year = varchar("death_year")
    val death_month = varchar("death_month")
    val death_day = varchar("death_day")
    val pro_played_first = varchar("pro_played_first")
    val pro_played_last = varchar("pro_played_last")
    val mlb_played_first = varchar("mlb_played_first")
    val mlb_played_last = varchar("mlb_played_last")
    val col_played_first = varchar("col_played_first")
    val col_played_last = varchar("col_played_last")
    val pro_managed_first = varchar("pro_managed_first")
    val pro_managed_last = varchar("pro_managed_last")
    val mlb_managed_first = varchar("mlb_managed_first")
    val mlb_managed_last = varchar("mlb_managed_last")
    val col_managed_first = varchar("col_managed_first")
    val col_managed_last = varchar("col_managed_last")
    val pro_umpired_first = varchar("pro_umpired_first")
    val pro_umpired_last = varchar("pro_umpired_last")
    val mlb_umpired_first = varchar("mlb_umpired_first")
    val mlb_umpired_last = varchar("mlb_umpired_last")
    val key_retro_manually_generated = int("key_retro_manually_generated")
}