package com.advanced_baseball_stats.repository.tables

import org.ktorm.schema.Table
import org.ktorm.schema.int
import org.ktorm.schema.varchar

object PitcherTable : Table<Nothing>("pitching")
{
    val gid = varchar("gid")
    val id = varchar("id")
    val team = varchar("team")
    val p_seq = int("p_seq")
    val stattype = varchar("stattype")
    val p_ipouts = int("p_ipouts")
    val p_noout = int("p_noout")
    val p_bfp = int("p_bfp")
    val p_h = int("p_h")
    val p_d = int("p_d")
    val p_t = int("p_t")
    val p_hr = int("p_hr")
    val p_r = int("p_r")
    val p_er = int("p_er")
    val p_w = int("p_w")
    val p_iw = int("p_iw")
    val p_k = int("p_k")
    val p_hbp = int("p_hbp")
    val p_wp = int("p_wp")
    val p_bk = int("p_bk")
    val p_sh = int("p_sh")
    val p_sf = int("p_sf")
    val p_sb = int("p_sb")
    val p_cs = int("p_cs")
    val p_pb = varchar("p_pb")
    val wp = int("wp")
    val lp = int("lp")
    val save = int("save")
    val p_gs = int("p_gs")
    val p_gf = int("p_gf")
    val p_cg = int("p_cg")
    val date = varchar("date")
    val number = int("number")
    val site = varchar("site")
    val vishome = varchar("vishome")
    val opp = varchar("opp")
    val win = int("win")
    val loss = int("loss")
    val tie = int("tie")
    val gametype = varchar("gametype")
    val box = varchar("box")
    val pbp = varchar("pbp")
}
